apiVersion: v1
appVersion: "1.0"
description: A Helm chart for creating a Carbyne Stack Amphora secret storage and management service.
name: amphora
version: 0.1.0
keywords:
- carbyne stack
- amphora
home: https://carbynestack.io
sources:
- https://github.com/carbynestack/amphora
maintainers:
- name: CarbyneStack.io
