spring:
  profiles: secretsharestore-minio

carbynestack:
  amphora:
    minio:
      endpoint: ${MINIO_ENDPOINT}
      bucket: minio-amphora-bucket
      access-key: dummy-key
      secret-key: dummy-secret
